#!/bin/bash
set -Eeuo pipefail

if [ "$#" -ne  2 ]; then 
    echo "Usage: ./build {filename.cu} {program_name}"
    exit 1
fi
if [ ! -d "__build" ] 
then
    #cd libwb/
    mkdir __build
    cd __build/
    cmake ..
    make -j4
    cd ../#..
fi
# module load cuda
export PATH=/usr/local/cuda-10.0/bin/:$PATH
nvcc $1 -o $2 -std=c++11 #-lwb
echo "Successfully built $2"